**import Library**

In [214]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from itertools import product
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
import math
from collections import deque

**Upload data**

In [215]:
covid= pd.read_csv('covid.csv')

covid.head()

   # age Sleep_problems  ... Loss_of_smell Loss_of_taste urticaria
0  1  19            yes  ...            no            no        no
1  2  28            yes  ...            no            no        no
2  3  40             no  ...            no            no        no
3  4  62            yes  ...            no            no        no
4  5  23            yes  ...            no            no        no

[5 rows x 23 columns]

**Delete extras**

In [216]:
covid= covid.drop(['#'], axis=1)
covid= covid.drop(['age'], axis=1)
covid.head()

  Sleep_problems Headache Diarrhea  ... Loss_of_smell Loss_of_taste urticaria
0            yes      yes      yes  ...            no            no        no
1            yes      yes       no  ...            no            no        no
2             no      yes       no  ...            no            no        no
3            yes      yes      yes  ...            no            no        no
4            yes      yes       no  ...            no            no        no

[5 rows x 21 columns]

In [217]:
covid.describe()

       Sleep_problems Headache Diarrhea  ... Loss_of_smell Loss_of_taste urticaria
count             487      486      487  ...           487           487       487
unique              2        3        4  ...             2             2         2
top                no       no       no  ...            no            no        no
freq              436      275      387  ...           380           425       479

[4 rows x 21 columns]

In [218]:
covid=covid.replace({'es':'Yes'});

In [219]:
covid=covid.replace({'Yes':'yes'});

In [220]:
covid=covid.replace({'No':'no'});

In [221]:
covid.describe()

       Sleep_problems Headache Diarrhea  ... Loss_of_smell Loss_of_taste urticaria
count             487      486      487  ...           487           487       487
unique              2        2        2  ...             2             2         2
top                no       no       no  ...            no            no        no
freq              436      283      410  ...           380           425       479

[4 rows x 21 columns]

In [222]:
from sklearn import preprocessing
covid=covid.drop_duplicates()
covid.replace(('yes', 'no'), (1 , 0), inplace=True)
covid.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4389: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

   Sleep_problems  Headache  Diarrhea  ...  Loss_of_smell  Loss_of_taste  urticaria
0               1       1.0         1  ...              0              0          0
1               1       1.0         0  ...              0              0          0
2               0       1.0         0  ...              0              0          0
3               1       1.0         1  ...              0              0          0
4               1       1.0         0  ...              0              0          0

[5 rows x 21 columns]

**Find trivial features**

In [187]:
covid['Sleep_problems'].value_counts()

0    248
1     39
Name: Sleep_problems, dtype: int64

In [103]:
covid['Headache'].value_counts()

0.0    157
1.0    129
Name: Headache, dtype: int64

In [104]:
covid['Diarrhea'].value_counts()

0    235
1     52
Name: Diarrhea, dtype: int64

In [105]:
covid['Abdominal_pain'].value_counts()

0    252
1     35
Name: Abdominal_pain, dtype: int64

In [106]:
covid['body_pain'].value_counts()

0    144
1    143
Name: body_pain, dtype: int64

In [107]:
covid['Body_discoloration'].value_counts()

0    265
1     22
Name: Body_discoloration, dtype: int64

In [108]:
covid['Cough'].value_counts()

0    144
1    143
Name: Cough, dtype: int64

In [109]:
covid['Fever'].value_counts()

1    164
0    123
Name: Fever, dtype: int64

In [110]:
covid['Ague'].value_counts()

0    249
1     38
Name: Ague, dtype: int64

In [111]:
covid['Sore_throat'].value_counts()

0    180
1    107
Name: Sore_throat, dtype: int64

In [112]:
covid['Fatigue'].value_counts()

0    163
1    124
Name: Fatigue, dtype: int64

In [113]:
covid['runny_nose'].value_counts()

0    213
1     74
Name: runny_nose, dtype: int64

In [114]:
covid['Chest_pain'].value_counts()

0    234
1     53
Name: Chest_pain, dtype: int64

In [115]:
covid['Decreased_appetite'].value_counts()

0    204
1     83
Name: Decreased_appetite, dtype: int64

In [116]:
covid['Vomit'].value_counts()

0    272
1     15
Name: Vomit, dtype: int64

In [117]:
covid['Nausea'].value_counts()

0    232
1     55
Name: Nausea, dtype: int64

In [118]:
covid['Sneezing'].value_counts()

0    249
1     38
Name: Sneezing, dtype: int64

In [119]:
covid['Shortness_of_breath'].value_counts()

0    190
1     97
Name: Shortness_of_breath, dtype: int64

In [120]:
covid['Loss_of_smell'].value_counts()

0    199
1     88
Name: Loss_of_smell, dtype: int64

In [121]:
covid['Loss_of_smell'].value_counts()

0    199
1     88
Name: Loss_of_smell, dtype: int64

In [122]:
covid['Loss_of_taste'].value_counts()

0    232
1     55
Name: Loss_of_taste, dtype: int64

In [123]:
covid['urticaria'].value_counts()

0    279
1      8
Name: urticaria, dtype: int64

**Remove trivial features**

In [223]:
covid.drop(['urticaria','Vomit','Body_discoloration','Abdominal_pain'], axis = 1,inplace=True)
covid

     Sleep_problems  Headache  ...  Loss_of_smell  Loss_of_taste
0                 1       1.0  ...              0              0
1                 1       1.0  ...              0              0
2                 0       1.0  ...              0              0
3                 1       1.0  ...              0              0
4                 1       1.0  ...              0              0
..              ...       ...  ...            ...            ...
482               0       1.0  ...              0              0
483               0       0.0  ...              1              1
484               0       0.0  ...              1              1
485               0       0.0  ...              1              1
486               0       1.0  ...              1              0

[287 rows x 17 columns]

In [224]:
covid=covid.drop_duplicates(keep=False)
covid.shape

(259, 17)

In [225]:
covid.describe()

       Sleep_problems    Headache  ...  Loss_of_smell  Loss_of_taste
count      259.000000  258.000000  ...     259.000000     259.000000
mean         0.104247    0.414729  ...       0.308880       0.196911
std          0.306172    0.493633  ...       0.462926       0.398435
min          0.000000    0.000000  ...       0.000000       0.000000
25%          0.000000    0.000000  ...       0.000000       0.000000
50%          0.000000    0.000000  ...       0.000000       0.000000
75%          0.000000    1.000000  ...       1.000000       0.000000
max          1.000000    1.000000  ...       1.000000       1.000000

[8 rows x 17 columns]

In [226]:
np.where(pd.isnull(covid))

(array([194]), array([1]))

In [227]:
covid=covid.drop(covid.index[194])
np.where(pd.isnull(covid))

(array([], dtype=int64), array([], dtype=int64))

In [228]:
np.where(pd.isnull(covid))

(array([], dtype=int64), array([], dtype=int64))

In [229]:
from sklearn import preprocessing
covid_data = covid.copy()

In [230]:
covid_data

     Sleep_problems  Headache  ...  Loss_of_smell  Loss_of_taste
2                 0       1.0  ...              0              0
5                 0       1.0  ...              0              0
9                 1       0.0  ...              0              0
10                0       0.0  ...              0              0
13                1       0.0  ...              0              0
..              ...       ...  ...            ...            ...
482               0       1.0  ...              0              0
483               0       0.0  ...              1              1
484               0       0.0  ...              1              1
485               0       0.0  ...              1              1
486               0       1.0  ...              1              0

[258 rows x 17 columns]

In [231]:
data = covid.append(covid_data, ignore_index=True)

data

     Sleep_problems  Headache  ...  Loss_of_smell  Loss_of_taste
0                 0       1.0  ...              0              0
1                 0       1.0  ...              0              0
2                 1       0.0  ...              0              0
3                 0       0.0  ...              0              0
4                 1       0.0  ...              0              0
..              ...       ...  ...            ...            ...
511               0       1.0  ...              0              0
512               0       0.0  ...              1              1
513               0       0.0  ...              1              1
514               0       0.0  ...              1              1
515               0       1.0  ...              1              0

[516 rows x 17 columns]

**normalize**

In [232]:
scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
names = data.columns
d = scaler.fit_transform(data)
DATA = pd.DataFrame(d, columns=names)
DATA

     Sleep_problems  Headache  ...  Loss_of_smell  Loss_of_taste
0               0.0       1.0  ...            0.0            0.0
1               0.0       1.0  ...            0.0            0.0
2               1.0       0.0  ...            0.0            0.0
3               0.0       0.0  ...            0.0            0.0
4               1.0       0.0  ...            0.0            0.0
..              ...       ...  ...            ...            ...
511             0.0       1.0  ...            0.0            0.0
512             0.0       0.0  ...            1.0            1.0
513             0.0       0.0  ...            1.0            1.0
514             0.0       0.0  ...            1.0            1.0
515             0.0       1.0  ...            1.0            0.0

[516 rows x 17 columns]

In [233]:
COVID = np.array(DATA)[:,:-1]
CLASS = np.array(DATA)[:,-1]

**Find-s algorithm**

In [235]:
def train(con, tar):
    for i, val in enumerate(tar):
        if val == 'yes' or "Yes":
            specific_h = con[i].copy()
            break
            
    for i, val in enumerate(con):
        if tar[i] == 'yes' or "Yes":
            for x in range(len(specific_h)):
                if val[x] != specific_h[x]:
                    specific_h[x] = '?'
                else:
                    pass
    return specific_h


print(find_s(COVID,CLASS))

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]

**Candidate Elimination algorithm**

In [246]:
def learn(con, tar):

    specific_h = con[0].copy()
    general_h = [["?" for i in range(len(specific_h))] for i in range(len(specific_h))]

    print("specific_h: ",specific_h)
    print("general_h: ",general_h)
    #print("concepts: ",con)

    for i, h in enumerate(con):
        if tar[i] == "yes":
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    specific_h[x] = '?'
                    general_h[x][x] = '?'

        if tar[i] == "no":
            for x in range(len(specific_h)):
                if h[x] != specific_h[x]:
                    general_h[x][x] = specific_h[x]
                else:
                    general_h[x][x] = '?'


    indices = [i for i, val in enumerate(general_h) if val == ['?', '?', '?', '?', '?', '?']]

    for i in indices:
        general_h.remove(['?', '?', '?', '?', '?', '?'])
    return specific_h, general_h

s_final,g_final = learn(COVID,CLASS)

print("\nFinal Specific_h:", s_final, sep="\n")

print("Final General_h:", g_final, sep="\n")

specific_h:  [0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
general_h:  [['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?']]

Final Specific_h:
[0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Final General_h:
[['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?']]

**train_test_split**

In [247]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(COVID,CLASS, test_size = 0.30, random_state = 0)

In [248]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

**naive_bayes**

In [249]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [252]:
yprob  =  classifier.predict(x_test)

In [258]:
confusion = confusion_matrix(y_test, yprob)
print(classification_report(y_test, yprob))
accuracy = accuracy_score(y_test,yprob)

print(accuracy)

              precision    recall  f1-score   support

         0.0       0.91      0.92      0.91       122
         1.0       0.69      0.67      0.68        33

    accuracy                           0.86       155
   macro avg       0.80      0.79      0.80       155
weighted avg       0.86      0.86      0.86       155

0.864516129032258

**KNN**

In [255]:
classifier = KNeighborsClassifier(n_neighbors=15)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=15)

In [256]:
yprob_1 = classifier.predict(x_test)

In [259]:
print(confusion_matrix(y_test, yprob_1))
print(classification_report(y_test, yprob_1))
accuracy = accuracy_score(y_test,yprob_1)

print(accuracy)

[[117   5]
 [ 16  17]]
              precision    recall  f1-score   support

         0.0       0.88      0.96      0.92       122
         1.0       0.77      0.52      0.62        33

    accuracy                           0.86       155
   macro avg       0.83      0.74      0.77       155
weighted avg       0.86      0.86      0.85       155

0.864516129032258

**Decision Tree**

In [261]:
clf = DecisionTreeClassifier(max_depth=8, criterion='entropy', random_state=1)
clf = clf.fit(x_train,y_train)

In [263]:
yprob_2 = clf.predict(x_test)

In [264]:
print(confusion_matrix(y_test, yprob_2))
print(classification_report(y_test, yprob_2))
accuracy = accuracy_score(y_test,yprob_2)

print(accuracy)

[[120   2]
 [ 10  23]]
              precision    recall  f1-score   support

         0.0       0.92      0.98      0.95       122
         1.0       0.92      0.70      0.79        33

    accuracy                           0.92       155
   macro avg       0.92      0.84      0.87       155
weighted avg       0.92      0.92      0.92       155

0.9225806451612903

**kmeans**

In [266]:
kmeans = KMeans(n_clusters = 3, max_iter = 300, random_state = 0)
kmeans.fit(x_train)

KMeans(n_clusters=3, random_state=0)

In [267]:
centers = kmeans.cluster_centers_
print(centers)

[[-0.31484842 -0.0234494   0.02763343 -0.26298175 -0.16366229  0.79591718
  -0.17122163 -0.07657299 -0.11214647 -0.11985403 -0.23094602 -0.28973482
   0.06957274 -0.34384803 -0.05842748 -0.23929743]
 [-0.13244373 -0.13525259 -0.04673562 -0.17084102 -0.15747955 -1.25641213
  -0.37256041 -0.28546804 -0.20720049 -0.08556355 -0.22016456 -0.29003824
  -0.16697719 -0.12679014 -0.32832918 -0.27628592]
 [ 1.09058392  0.33592011  0.02282576  1.03323882  0.74693661  0.47524073
   1.20354477  0.77966461  0.71350818  0.48654508  1.04983404  1.34516697
   0.15763104  1.15477093  0.81937785  1.18562252]]

**id3**

In [265]:
class Node:
    def __init__(self):
        self.value = None
        self.next = None
        self.childs = None


class DecisionTreeClassifier:
    def __init__(self, X, feature_names, labels):
        self.X = X
        self.feature_names = feature_names
        self.labels = labels
        self.labelCategories = list(set(labels))
        self.labelCategoriesCount = [list(labels).count(x) for x in self.labelCategories]
        self.node = None
        self.entropy = self._get_entropy([x for x in range(len(self.labels))])  # calculates the initial entropy

    def _get_entropy(self, x_ids):
        labels = [self.labels[i] for i in x_ids]
      
        label_count = [labels.count(x) for x in self.labelCategories]
    
        entropy = sum([-count / len(x_ids) * math.log(count / len(x_ids), 2) if count else 0 for count in label_count])
        return entropy

    def _get_information_gain(self, x_ids, feature_id):
      
        info_gain = self._get_entropy(x_ids)
        
        x_features = [self.X[x][feature_id] for x in x_ids]
        
        feature_vals = list(set(x_features))
        
        feature_vals_count = [x_features.count(x) for x in feature_vals]
        
        feature_vals_id = [
            [x_ids[i]
            for i, x in enumerate(x_features)
            if x == y]
            for y in feature_vals
        ]

        
        info_gain = info_gain - sum([val_counts / len(x_ids) * self._get_entropy(val_ids)
                                     for val_counts, val_ids in zip(feature_vals_count, feature_vals_id)])

        return info_gain

    def _get_feature_max_information_gain(self, x_ids, feature_ids):

        
        features_entropy = [self._get_information_gain(x_ids, feature_id) for feature_id in feature_ids]
        
        max_id = feature_ids[features_entropy.index(max(features_entropy))]

        return self.feature_names[max_id], max_id

    def id3(self):

        x_ids = [x for x in range(len(self.X))]
        feature_ids = [x for x in range(len(self.feature_names))]
        self.node = self._id3_recv(x_ids, feature_ids, self.node)
        print('')

    def _id3_recv(self, x_ids, feature_ids, node):

        if not node:
            node = Node()  

        # sorted labels by instance id
        labels_in_features = [self.labels[x] for x in x_ids]

        # if all the example have the same class (pure node), return node
        if len(set(labels_in_features)) == 1:
            node.value = self.labels[x_ids[0]]
            return node

        
        if len(feature_ids) == 0:
            node.value = max(set(labels_in_features), key=labels_in_features.count)  # compute mode
            return node
        
        best_feature_name, best_feature_id = self._get_feature_max_information_gain(x_ids, feature_ids)
        node.value = best_feature_name
        node.childs = []
        # value of the chosen feature for each instance
        feature_values = list(set([self.X[x][best_feature_id] for x in x_ids]))
        # loop through all the values
        for value in feature_values:
            child = Node()
            child.value = value  
            node.childs.append(child)  
            child_x_ids = [x for x in x_ids if self.X[x][best_feature_id] == value]
            if not child_x_ids:
                child.next = max(set(labels_in_features), key=labels_in_features.count)
                print('')
            else:
                if feature_ids and best_feature_id in feature_ids:
                    to_remove = feature_ids.index(best_feature_id)
                    feature_ids.pop(to_remove)
                # recursively call the algorithm
                child.next = self._id3_recv(child_x_ids, feature_ids, child.next)
        return node

    def printTree(self):
        if not self.node:
            return
        nodes = deque()
        nodes.append(self.node)
        while len(nodes) > 0:
            node = nodes.popleft()
            print(node.value)
            if node.childs:
                for child in node.childs:
                    print('({})'.format(child.value))
                    nodes.append(child.next)
            elif node.next:
                print(node.next)

tree_clf = DecisionTreeClassifier(X=X_train, feature_names=feature_vector[:-1], labels=Y_train)
print("System entropy {:.4f}".format(tree_clf.entropy))

System entropy 0.7038