In [20]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [6]:
# making data frame from json file
data = pd.read_csv("covid.csv")
 
# display
data

       # age Sleep_problems  ... Loss_of_smell Loss_of_taste urticaria
0      1  19            yes  ...            no            no        no
1      2  28            yes  ...            no            no        no
2      3  40             no  ...            no            no        no
3      4  62            yes  ...            no            no        no
4      5  23            yes  ...            no            no        no
..   ...  ..            ...  ...           ...           ...       ...
482  483  26             no  ...            no            no        no
483  484  51             no  ...           yes           yes        no
484  485  32             no  ...           yes           yes        no
485  486  30             no  ...           yes           yes        no
486  487  27             no  ...           yes            no        no

[487 rows x 23 columns]

In [7]:
data.head().T

                       0    1    2    3    4
#                      1    2    3    4    5
age                   19   28   40   62   23
Sleep_problems       yes  yes   no  yes  yes
Headache             yes  yes  yes  yes  yes
Diarrhea             yes   no   no  yes   no
Abdominal_pain       yes   no   no  yes   no
body_pain            yes  yes  yes  yes  yes
Body_discoloration    no   no  yes   no   no
Cough                 no  yes  yes  yes   no
Fever                 no   no   no   no   no
Ague                  no   no   no   no   no
Sore_throat           no   no   no   no   no
Fatigue               no   no   no   no   no
runny_nose            no   no   no   no   no
Chest_pain            no   no   no   no   no
Decreased_appetite    no   no   no   no   no
Vomit                 no   no   no   no   no
Nausea                no   no   no   no   no
Sneezing              no   no   no   no   no
Shortness_of_breath   no   no   no   no   no
Loss_of_smell         no   no   no   no   no
Loss_of_taste         no   no   no   no   no
urticaria             no   no   no   no   no

In [8]:
#get some information about our Data-Set
data.info()
data.describe().transpose()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 487 entries, 0 to 486
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   #                    487 non-null    int64
 1   age                  487 non-null    object
 2   Sleep_problems       487 non-null    object
 3   Headache             486 non-null    object
 4   Diarrhea             487 non-null    object
 5   Abdominal_pain       487 non-null    object
 6   body_pain            487 non-null    object
 7   Body_discoloration   487 non-null    object
 8   Cough                487 non-null    object
 9   Fever                487 non-null    object
 10  Ague                 487 non-null    object
 11  Sore_throat          487 non-null    object
 12  Fatigue              487 non-null    object
 13  runny_nose           487 non-null    object
 14  Chest_pain           487 non-null    object
 15  Decreased_appetite   487 non-null    object
 16  Vomit                487 non-null    object
 17  Nausea               487 non-null    object
 18  Sneezing             487 non-null    object
 19  Shortness_of_breath  487 non-null    object
 20  Loss_of_smell        487 non-null    object
 21  Loss_of_taste        487 non-null    object
 22  urticaria            487 non-null    object
dtypes: int64(1), object(22)
memory usage: 87.6+ KB

   count   mean         std  min    25%    50%    75%    max
#  487.0  244.0  140.729054  1.0  122.5  244.0  365.5  487.0

In [9]:
# check if there are any Null values
data.isnull().sum()

#                      0
age                    0
Sleep_problems         0
Headache               1
Diarrhea               0
Abdominal_pain         0
body_pain              0
Body_discoloration     0
Cough                  0
Fever                  0
Ague                   0
Sore_throat            0
Fatigue                0
runny_nose             0
Chest_pain             0
Decreased_appetite     0
Vomit                  0
Nausea                 0
Sneezing               0
Shortness_of_breath    0
Loss_of_smell          0
Loss_of_taste          0
urticaria              0
dtype: int64

In [10]:
# replacing na values in college with No college
data["Headache"].fillna("yes", inplace = True)

In [11]:
data

       # age Sleep_problems  ... Loss_of_smell Loss_of_taste urticaria
0      1  19            yes  ...            no            no        no
1      2  28            yes  ...            no            no        no
2      3  40             no  ...            no            no        no
3      4  62            yes  ...            no            no        no
4      5  23            yes  ...            no            no        no
..   ...  ..            ...  ...           ...           ...       ...
482  483  26             no  ...            no            no        no
483  484  51             no  ...           yes           yes        no
484  485  32             no  ...           yes           yes        no
485  486  30             no  ...           yes           yes        no
486  487  27             no  ...           yes            no        no

[487 rows x 23 columns]

In [12]:
#check for nan values
data.isnull().values.any()

False

In [13]:
data['age'].isnull().values.any()

False

In [14]:
check_for_nan = data['age'].isnull().values.any()
print (check_for_nan)

False

In [15]:
data.isnull().sum().sum()

0

In [16]:
#replace nan value with 0
data.fillna(0)

       # age Sleep_problems  ... Loss_of_smell Loss_of_taste urticaria
0      1  19            yes  ...            no            no        no
1      2  28            yes  ...            no            no        no
2      3  40             no  ...            no            no        no
3      4  62            yes  ...            no            no        no
4      5  23            yes  ...            no            no        no
..   ...  ..            ...  ...           ...           ...       ...
482  483  26             no  ...            no            no        no
483  484  51             no  ...           yes           yes        no
484  485  32             no  ...           yes           yes        no
485  486  30             no  ...           yes           yes        no
486  487  27             no  ...           yes            no        no

[487 rows x 23 columns]

In [17]:
data

       # age Sleep_problems  ... Loss_of_smell Loss_of_taste urticaria
0      1  19            yes  ...            no            no        no
1      2  28            yes  ...            no            no        no
2      3  40             no  ...            no            no        no
3      4  62            yes  ...            no            no        no
4      5  23            yes  ...            no            no        no
..   ...  ..            ...  ...           ...           ...       ...
482  483  26             no  ...            no            no        no
483  484  51             no  ...           yes           yes        no
484  485  32             no  ...           yes           yes        no
485  486  30             no  ...           yes           yes        no
486  487  27             no  ...           yes            no        no

[487 rows x 23 columns]

In [27]:
#drop age column=missval or nan val
data.drop("age",axis=1,inplace=True)

In [28]:
data

       # Sleep_problems Headache  ... Loss_of_smell Loss_of_taste urticaria
0      1            yes      yes  ...            no            no        no
1      2            yes      yes  ...            no            no        no
2      3             no      yes  ...            no            no        no
3      4            yes      yes  ...            no            no        no
4      5            yes      yes  ...            no            no        no
..   ...            ...      ...  ...           ...           ...       ...
482  483             no      yes  ...            no            no        no
483  484             no       no  ...           yes           yes        no
484  485             no       no  ...           yes           yes        no
485  486             no       no  ...           yes           yes        no
486  487             no      yes  ...           yes            no        no

[487 rows x 22 columns]

In [47]:
#replace yes and no with 0 and 1

In [ ]:
#make concept
#اگر مثلا همه شون صفر بود صفر بشه و در غیر اینصورت یک بشه

In [ ]:
#حالا نورمالیزه-البته عزیزم اینجا دیگه نیازی نیست چون دیگه همشونو بالا میخوایم صفرو یک کنیم کخ ارور بود و نشد

In [ ]:
#اینجا بیایم سورت کنیم بر حسب یه مقداری

In [ ]:
#اینجاهم داده های تکراری رو اوکی کنیم

In [ ]:
#اینجا فکنم باید با هیت مپ یا یه همچین چیزایی باید فیچرهارو رسم کنیم و به ترتیب صعودی باشه که اون 5 تا کم اهمیتو بهمون بده

In [ ]:
#اینجام دیگه الگوریتم ها حواخد بود dear

In [ ]:
#thanks for your attention Dr.Torabzadeh(Ashkim)